# Document:
# http://simiki.org/docs/configuration.html

url: http://wiki.phixyn.com
title: Wiki · Phixyn
keywords: personal, wiki, stuff
description: Phixyn's Personal Wiki \o/
author: Phixyn
theme: yasimple_x2

# Category aliases
category:
  - name: continuous-integration
    label: CI/CD
  - name: front-end-development
    label: Front-End Development
  - name: ios
    label: iOS
  - name: machine-learning
    label: Machine Learning
  - name: macos
    label: MacOS
  - name: version-control
    label: Version Control
  - name: web-development
    label: Web Development

# Parser
markdown:
  - fenced_code
  - extra
  - codehilite(css_class=hlcode, linenums=True)
  - toc(title=Table of Contents)